// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Task struct {
	TaskID    int32     `json:"task_id"`
	UserID    int32     `json:"user_id"`
	Task      string    `json:"task"`
	Status    bool      `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	UserID    int32     `json:"user_id"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
}
