// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, username string) (User, error)
	DeleteTask(ctx context.Context, taskID int32) error
	DeleteUser(ctx context.Context, userID int32) error
	GetTask(ctx context.Context, taskID int32) (Task, error)
	GetUser(ctx context.Context, userID int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListTasks(ctx context.Context) ([]Task, error)
	ListTasksByUser(ctx context.Context, userID int32) ([]Task, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error)
}

var _ Querier = (*Queries)(nil)
