// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (user_id, task)
VALUES ($1, $2)
RETURNING task_id, user_id, task, status, created_at
`

type CreateTaskParams struct {
	UserID int32  `json:"user_id"`
	Task   string `json:"task"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask, arg.UserID, arg.Task)
	var i Task
	err := row.Scan(
		&i.TaskID,
		&i.UserID,
		&i.Task,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE task_id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, taskID int32) error {
	_, err := q.db.ExecContext(ctx, deleteTask, taskID)
	return err
}

const getTask = `-- name: GetTask :one
SELECT task_id, user_id, task, status, created_at FROM tasks
WHERE task_id = $1 LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, taskID int32) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, taskID)
	var i Task
	err := row.Scan(
		&i.TaskID,
		&i.UserID,
		&i.Task,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT task_id, user_id, task, status, created_at FROM tasks
ORDER BY created_at DESC
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.UserID,
			&i.Task,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByUser = `-- name: ListTasksByUser :many
SELECT task_id, user_id, task, status, created_at FROM tasks
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTasksByUser(ctx context.Context, userID int32) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.TaskID,
			&i.UserID,
			&i.Task,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET task = $2, status = $3
WHERE task_id = $1
RETURNING task_id, user_id, task, status, created_at
`

type UpdateTaskParams struct {
	TaskID int32  `json:"task_id"`
	Task   string `json:"task"`
	Status bool   `json:"status"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask, arg.TaskID, arg.Task, arg.Status)
	var i Task
	err := row.Scan(
		&i.TaskID,
		&i.UserID,
		&i.Task,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks
SET status = $2
WHERE task_id = $1
RETURNING task_id, user_id, task, status, created_at
`

type UpdateTaskStatusParams struct {
	TaskID int32 `json:"task_id"`
	Status bool  `json:"status"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskStatus, arg.TaskID, arg.Status)
	var i Task
	err := row.Scan(
		&i.TaskID,
		&i.UserID,
		&i.Task,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
